language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "cxsonar_sonar-scanner-maven" 
    token:
      secure: a3b6fcd14f2101ff759ee5f70c1bc0563f6f28de # encrypted value of your token

sjdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
