language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'

before_cache:
  - rm -rf $HOME/.m2/repository/org/codehaus/mojo/sonar-maven-plugin

addons:
  sonarcloud:
    organization: "cxsonar_sonar-scanner-maven" # the key of the org you chose at step #3
    token:
      secure: 6671057b1d77eac3ca564d6ef60dcad280a223f7 # encrypted value of your token
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
